### ISSUE TITLE
Bug: Authority cannot be found

### ISSUE THREAD

**Issue by wrongecho** [derpenstiltskin/onedriveshortcuts#1]
Hi there,

Great project!

I've run into a bug when connecting with Connect-ODS with a client secret. 

This seems to be caused when you call Get-MsalToken without the AzureCloudInstance parameter. Adding the parameter and setting it as appropriate (1 for most use cases) fixes the issue. 

_The property 'Authority' cannot be found on this object. Verify the property exists._

**Comment by derpenstiltskin** [comment]
Thanks for submitting the issue. I've added a parameter in the latest commit to specify AzureCloudInstance and for it to default to 1. I still need to bug test the change out before pushing to release.

**Comment by wrongecho** [comment]
Great stuff, thank you!
